name: example
description: GetWidget Demo app

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^8.0.1 
  shared_preferences: ^2.0.8
  getwidget: ^4.0.0
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.0.3
  url_launcher: ^6.1.2  
  sqflite: ^2.2.6
  flutter_slidable: ^0.6.0
  local_auth: ^2.1.3
  image_cropper: ^3.0.1
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0
  camera: ^0.10.5+2
  mobile_scanner: ^3.2.0
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0
  flutter_tts: ^3.2.2
  pdf: ^3.6.4
  printing: ^5.9.0
  barcode_widget: ^2.0.4
  uuid: ^3.0.6
  responsive_sizer: ^3.2.0
  http: ^0.13.6
  flutter_riverpod: ^2.4.9
  mockito: ^5.0.7
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/subject_1.jpg
    - assets/subject_2.jpg
    - assets/subject_3.jpg
    - assets/subject_4.jpg
    - assets/subject_5.jpg

msix_config:
  display_name: e-learning
  publisher_display_name: e-learning pbp
  identity_name: com.elearningpbp
  logo_path: D:\Downloads\ic_launcher\1024.png
  msix_version: 1.0.0.0
  capabilities: internetClient